#!/usr/bin/env python3
"""Render the monolithic NeMo Guardrails ConfigMap for cluster deploy.

Generates guardrails/config/nemoguard/config.yaml via generate_config.py using
values from deploy/overlays/ci-testing/cluster.env, then emits a Kubernetes
ConfigMap manifest with every file the nemoguard profile needs:

  config.yaml, prompts.yml, rails.co, actions.py, topic_policy.co
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import sys
import tempfile
from pathlib import Path

import yaml

AGENT_DIR = Path(__file__).resolve().parents[2]
GUARDRAILS_DIR = AGENT_DIR / "guardrails"
CONFIG_DIR = GUARDRAILS_DIR / "config" / "nemoguard"
GENERATE_CONFIG_PATH = GUARDRAILS_DIR / "generate_config.py"
DEFAULT_CLUSTER_ENV = (
    AGENT_DIR / "deploy" / "overlays" / "ci-testing" / "cluster.env.example"
)
DEFAULT_OUTPUT = AGENT_DIR / "deploy" / "manifests" / "02-guardrails-configmap.yaml"

CONFIGMAP_NAME = "langgraph-guardrailed-agent-guardrails-config"
EMBED_FILES = (
    "config.yaml",
    "prompts.yml",
    "rails.co",
    "actions.py",
    "topic_policy.co",
)


def _load_generate_config():
    spec = importlib.util.spec_from_file_location(
        "generate_config", GENERATE_CONFIG_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {GENERATE_CONFIG_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_cluster_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise FileNotFoundError(f"Cluster env file not found: {path}")
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        values[key] = value
    return values


def _apply_env(values: dict[str, str]) -> None:
    # Never load API keys into the render environment — cluster ConfigMaps must
    # not embed secrets. Runtime auth uses the NemoGuardrails CR Secret env.
    skip_keys = {"NVIDIA_API_KEY", "CONTENT_SAFETY_API_KEY", "TOPIC_CONTROL_API_KEY"}
    for key, value in values.items():
        if key in skip_keys:
            continue
        os.environ[key] = value
    os.environ["GUARDRAILS_OMIT_NIM_API_KEYS"] = "1"


def _build_config_yaml(tmp_dir: Path) -> Path:
    generate_config = _load_generate_config()
    config_path = tmp_dir / "config.yaml"
    shutil.copy(CONFIG_DIR / "config.yaml.example", config_path)
    generate_config.generate_config(str(config_path), omit_nim_api_keys=True)
    return config_path


def render_configmap(cluster_env: Path, output: Path) -> None:
    values = _load_cluster_env(cluster_env)
    _apply_env(values)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        config_path = _build_config_yaml(tmp_dir)

        data: dict[str, str] = {}
        data["config.yaml"] = config_path.read_text(encoding="utf-8")
        for name in EMBED_FILES:
            if name == "config.yaml":
                continue
            data[name] = (CONFIG_DIR / name).read_text(encoding="utf-8")

    manifest = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": CONFIGMAP_NAME,
            "labels": {
                "app.kubernetes.io/name": "langgraph-guardrailed-agent-guardrails",
                "app.kubernetes.io/component": "nemoguardrails",
            },
        },
        "data": data,
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        env_ref = str(cluster_env.relative_to(AGENT_DIR))
    except ValueError:
        env_ref = str(cluster_env)
    header = (
        "# Generated by deploy/scripts/render_guardrails_configmap.py — do not edit.\n"
        f"# Source env: {env_ref}\n"
    )
    output.write_text(
        header + yaml.safe_dump(manifest, sort_keys=False),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cluster-env",
        type=Path,
        default=DEFAULT_CLUSTER_ENV,
        help="Env file with cluster LLM/NIM settings (default: cluster.env.example)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path for rendered ConfigMap manifest",
    )
    args = parser.parse_args()

    cluster_env = args.cluster_env
    if cluster_env.name.endswith(".example"):
        local_env = cluster_env.with_name("cluster.env")
        if local_env.is_file():
            cluster_env = local_env

    try:
        render_configmap(cluster_env, args.output)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Rendered {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
